name: Yanp
main: io.github.nheir.yanp.Yanp
version: 1.3

commands:
  nick:
    description: Set/unset a nickname
    usage: /nick [nickname]
    permission: simplenick.nick
    permission-message: You don't have <permission>
      
permissions:
  yanp.nick:
    description: Allow to set or unset nickname
    default: true
